sudo: false

cache:
  npm: false

language: node_js

node_js:
  - 12


after_success:
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov
  - ./node_modules/.bin/codecov
  - npm run coverage
