sudo: false

cache:
  npm: false

language: node_js

node_js:
  - 12


after_success:
  - ./node_modules/codecov/bin/codecov -e TRAVIS_NODE_VERSION -f coverage/*.json
  - ./node_modules/codecov/bin/codecov -e TRAVIS_NODE_VERSION 
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json